apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-orbit-api-ingress
  labels:
    app: cloud-orbit-api
  namespace: "{{ .Values.namespace }}"
spec:
  rules:
  - host: "{{ .Values.host }}"
    http:
      paths:
        - path: /backend/
          pathType: Prefix
          backend:
            service:
              name: cloud-orbit-api-service
              port:
                number: 80