apiVersion: v1
kind: Service
metadata:
  name: cloud-orbit-api-service
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    app: cloud-orbit-api
  type: ClusterIP
  # clusterIP: None
  ports:
    - name: cloud-orbit-api
      port: 80
      targetPort: 8000
      protocol: TCP
