name: Upload Python Package

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  test:
    name: Poetry Python
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run pytest
        run: poetry run pytest

      - name: Read Version Number
        id: read-version
        run: |
          VERSION=$(cat version.txt)  # Read version from file
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT  # Add to environment variables
            
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.3
        with:
          current-version: "${{ steps.read-version.outputs.VERSION }}"
          version-fragment: 'bug'

      - name: Commit Updated Version
        run: |
          echo "${{ steps.bump_version.outputs.next-version }}"
          echo ${{ steps.bump_version.outputs.next-version }}
          echo "${{ steps.bump_version.outputs.next-version }}" > version.txt
          sed -i "s/tag: \".*\"/tag: \"${{ steps.bump_version.outputs.next-version }}\"/" microservice/helm/values.yaml
          sed -i '0,/^version =/s/^version =.*/version = "${{ steps.bump_version.outputs.next-version }}"/' pyproject.toml

      - name: Build package
        run: poetry build

      - name: Publish package
        run: poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --build-arg CLOUD_ORBIT_API="cloud-orbit-api==${{ steps.bump_version.outputs.next-version }}" -t ${{ secrets.DOCKERHUB_USERNAME }}/cloud-orbit-api-image:${{ steps.bump_version.outputs.next-version }} microservice

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloud-orbit-api-image:${{ steps.bump_version.outputs.next-version }}

      - name: Commit Updated Version
        run: |
          echo "${{ steps.bump_version.outputs.next-version }}"
          echo ${{ steps.bump_version.outputs.next-version }}
          echo "${{ steps.bump_version.outputs.next-version }}" > version.txt
          sed -i "s/tag: \".*\"/tag: \"${{ steps.bump_version.outputs.next-version }}\"/" /microservice/helm/values.yaml

      - uses: stefanzweifel/git-auto-commit-action@v5